version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: eyehealth-minio
    ports:
      - "9000:9000"      # API端口
      - "9001:9001"      # 控制台端口
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - eyehealth-network

  # MinIO客户端，用于初始化存储桶
  minio-init:
    image: minio/mc:latest
    container_name: eyehealth-minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin123;
      /usr/bin/mc mb myminio/eyehealth-reports --ignore-existing;
      /usr/bin/mc mb myminio/eyehealth-products --ignore-existing;
      /usr/bin/mc mb myminio/eyehealth-uploads --ignore-existing;
      /usr/bin/mc policy set public myminio/eyehealth-products;
      /usr/bin/mc policy set public myminio/eyehealth-uploads;
      echo 'MinIO buckets initialized successfully';
      "
    networks:
      - eyehealth-network

volumes:
  minio_data:
    driver: local

networks:
  eyehealth-network:
    driver: bridge





