version: '3.8'

services:
  # 数据库服务
  postgres:
    image: postgres:15
    container_name: eyehealth-postgres
    environment:
      POSTGRES_DB: eyehealth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eyehealth-network

  redis:
    image: redis:7-alpine
    container_name: eyehealth-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - eyehealth-network

  # 存储服务
  minio:
    image: minio/minio:latest
    container_name: eyehealth-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - eyehealth-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  eyehealth-network:
    driver: bridge






